version: '3.4'
services:
  neo4j:
    image: neo4j:4.4.26-community
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - "C:/tmp/neo4j_data:/data" # need to create windows folder manually
